version: '3.9'

services:
  jrema:
    image: jrema
    platform: linux/amd64
    build: ./src
    volumes:
      - rema-static:/home/node/app/static
  
  jrema-dev:
    image: jrema-dev
    platform: linux/amd64
    build:
      dockerfile: devcontainer.Dockerfile
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    volumes:
      - .:/home/ubuntu/app
      - rema-static:/home/ubuntu/static

volumes:
  rema-static: